version: '3'

services:
    php:
        container_name: ${PROJECT_SLUG}-php
        build:
            context: ./.docker/php
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www/html
    nginx:
        container_name: ${PROJECT_SLUG}-nginx
        image: nginx
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/html
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    postgres:
        container_name: ${PROJECT_SLUG}-postgres
        image: postgres
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - "5432:5432"
